name: fcurrency

volumes:
  static_volume:

services:

  redis:
    image: redis:alpine3.18
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - REDIS_URI=redis://redis:6379/0
    volumes:
      - static_volume:/static
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      redis:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - REDIS_URI=redis://redis:6379/0
    volumes:
      - .data/logs:/backend/data/logs
    command: celery -A config.celery worker -l warning -E --logfile=./data/logs/celery-worker.log
    depends_on:
      backend:
        condition: service_started

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - REDIS_URI=redis://redis:6379/0
    volumes:
      - .data/logs:/backend/data/logs
    command: celery -A config beat -l warning  --logfile=./data/logs/celery-beat.log
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: nginx:1.25.2-alpine3.18-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx_loc.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles/static/
    depends_on:
      backend:
        condition: service_started
